babel language: english
title: Thesis Template
mysubtitle: A novel approach for markdown document creation
date: 31.07.
period: 29.02.-31.07.
author: Martin Goth
advisor: Alfred J. Kwack
examiner: Prof. Dusentrieb
latex input: tex/header
latex input: tex/begin
latex input: introduction