# Introduction

## Meta Data

All meta tags of the thesis are specified at the beginning of `index.mmd`. If not specified otherwise, the tags are obligatory.

##### Known bug
The content of the meta-tag must be ASCII only

babel language
:   Is to be set to the thesis main language. Possible options are `ngerman` or `english`

title
:   The title of the thesis

mysubtitle
:   *optional* Longer subtitle of the thesis

date
:   The day of submission

period
:   The period in which you are supposed to write your thesis

author
:   The person that is writing your thesis

examiner
:   Professors or other authorized personal that is supposed to grade your thesis

advisor
:   The person that is actually supervising and grading your thesis